name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: rafigriffin11/Final_2
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Debug Checkout
        run: |
          git branch
          git remote -v
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.0.0'
          
      - name: Install dependencies
        run: npm install
        
      - name: Cypress run
        uses: cypress-io/github-action@v6