name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Set up Node.js 
        uses: actions/setup-node@v3 
        with: 
          node-version: '22.0.0' 
      - name: Installdependencies 
        run: npm
      - name: Cypress run
        uses: cypress-io/github-action@v6
