name: OWASP ZAP Baseline Scan

on: 
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start OWASP ZAP
        run: docker run -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t https://thinking-tester-contact-list.herokuapp.com/